<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::table('animals')->insert([
            [
                'common_name' => 'African Lion',
                'conservation_status' => 'Vulnerable',
                'weight' => '190.00',
                'height' => '1.2',
                'length' => '2.8',
                'locale' => 'Africa',
                'habitat' => 'Savanna',
                'diet' => 'Carnivore',
                'reproduction' => 'Sexual',
                'life_span' => '10-14 years',
                'color' => 'Golden brown',
                'danger_level' => 'Dangerous',
                'treatment_necessity' => 'Urgent',
                'prevention' => 'Avoid close contact; stay inside vehicles in reserves.',
                'description' => 'Large predatory cat living in groups called prides; apex predator of the African plains.',
                'inaturalist_id' => 12345,
                'gbif_id' => 56789,
                'specie_id' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'common_name' => 'Giant Panda',
                'conservation_status' => 'Vulnerable',
                'weight' => '100.00',
                'height' => '0.9',
                'length' => '1.8',
                'locale' => 'China',
                'habitat' => 'Temperate Forest',
                'diet' => 'Herbivore',
                'reproduction' => 'Sexual',
                'life_span' => '20 years',
                'color' => 'Black and white',
                'danger_level' => 'Mild',
                'treatment_necessity' => 'None',
                'prevention' => 'Do not disturb wild pandas; avoid feeding or approaching them.',
                'description' => 'Large bear species that primarily eats bamboo; symbol of wildlife conservation.',
                'inaturalist_id' => 54321,
                'gbif_id' => 67890,
                'specie_id' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'common_name' => 'Monarch Butterfly',
                'conservation_status' => 'Near Threatened',
                'weight' => '0.0005',
                'height' => '0.01',
                'length' => '0.1',
                'locale' => 'North America',
                'habitat' => 'Meadows',
                'diet' => 'Nectarivore',
                'reproduction' => 'Sexual',
                'life_span' => '6-8 months',
                'color' => 'Orange and black',
                'danger_level' => 'Harmless',
                'treatment_necessity' => 'None',
                'prevention' => 'Avoid destroying milkweed plants; protect pollinator habitats.',
                'description' => 'Migratory butterfly species known for its long-distance travel between North and Central America.',
                'inaturalist_id' => 98765,
                'gbif_id' => 13579,
                'specie_id' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'common_name' => 'King Cobra',
                'conservation_status' => 'Vulnerable',
                'weight' => '6.00',
                'height' => '0.3',
                'length' => '3.5',
                'locale' => 'Southeast Asia',
                'habitat' => 'Rainforest',
                'diet' => 'Carnivore',
                'reproduction' => 'Sexual',
                'life_span' => '20 years',
                'color' => 'Olive green with light bands',
                'danger_level' => 'Extreme',
                'treatment_necessity' => 'Critical',
                'prevention' => 'Stay calm and move away slowly if encountered; seek immediate medical attention for bites.',
                'description' => 'The world’s longest venomous snake; feeds mainly on other snakes and has potent neurotoxic venom.',
                'inaturalist_id' => 24680,
                'gbif_id' => 11223,
                'specie_id' => 4,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'common_name' => 'Emperor Penguin',
                'conservation_status' => 'Near Threatened',
                'weight' => '30.00',
                'height' => '1.1',
                'length' => '1.2',
                'locale' => 'Antarctica',
                'habitat' => 'Ice and Ocean',
                'diet' => 'Piscivore',
                'reproduction' => 'Sexual',
                'life_span' => '15-20 years',
                'color' => 'Black and white with yellow patches',
                'danger_level' => 'Harmless',
                'treatment_necessity' => 'None',
                'prevention' => 'Avoid disturbing colonies and maintain distance from nesting areas.',
                'description' => 'The largest penguin species; breeds during the Antarctic winter and feeds mainly on fish and krill.',
                'inaturalist_id' => 33445,
                'gbif_id' => 55667,
                'specie_id' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
