<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PlantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::table('plants')->insert([
            [
                'common_name' => 'Oak Tree',
                'conservation_status' => 'Least Concern',
                'type' => 'Tree',
                'growth_form' => 'Deciduous',
                'leaf_type' => 'Lobed',
                'leaf_arrangement' => 'Alternate',
                'fruit_type' => 'Nut',
                'root_type' => 'Taproot',
                'soil' => 'Loamy',
                'sunlight' => 'Full Sun',
                'water' => 'Medium',
                'reproduction' => 'Sexual',
                'height' => 30.0,
                'locale' => 'Northern Hemisphere',
                'habitat' => 'Temperate Forest',
                'diet' => 'Autotroph',
                'life_span' => '100-300 years',
                'growth_time' => 10.0,
                'color' => 'Green',
                'toxicity_level' => 'Non-toxic',
                'treatment_necessity' => 'None',
                'description' => 'Large deciduous tree known for strength, longevity, and acorn production.',
                'inaturalist_id' => 10001,
                'gbif_id' => 20001,
                'specie_id' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'common_name' => 'Sunflower',
                'conservation_status' => 'Least Concern',
                'type' => 'Herb',
                'growth_form' => 'Annual',
                'leaf_type' => 'Simple',
                'leaf_arrangement' => 'Alternate',
                'fruit_type' => 'Achene',
                'root_type' => 'Taproot',
                'soil' => 'Loamy',
                'sunlight' => 'Full Sun',
                'water' => 'Medium',
                'reproduction' => 'Sexual',
                'height' => 3.0,
                'locale' => 'North America',
                'habitat' => 'Open Fields',
                'diet' => 'Autotroph',
                'life_span' => '1 year',
                'growth_time' => 0.5,
                'color' => 'Yellow',
                'toxicity_level' => 'Non-toxic',
                'treatment_necessity' => 'None',
                'description' => 'Tall annual plant with large yellow flower heads that follow the sun.',
                'inaturalist_id' => 10002,
                'gbif_id' => 20002,
                'specie_id' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'common_name' => 'Venus Flytrap',
                'conservation_status' => 'Vulnerable',
                'type' => 'Herb',
                'growth_form' => 'Perennial',
                'leaf_type' => 'Simple',
                'leaf_arrangement' => 'Rosette',
                'fruit_type' => 'Capsule',
                'root_type' => 'Fibrous',
                'soil' => 'Peaty',
                'sunlight' => 'Full Sun',
                'water' => 'High',
                'reproduction' => 'Sexual and Asexual',
                'height' => 0.2,
                'locale' => 'North and South Carolina, USA',
                'habitat' => 'Wetlands',
                'diet' => 'Carnivorous',
                'life_span' => '20 years',
                'growth_time' => 1.0,
                'color' => 'Green and red',
                'toxicity_level' => 'Non-toxic',
                'treatment_necessity' => 'None',
                'description' => 'Carnivorous plant that traps insects with rapid leaf movement.',
                'inaturalist_id' => 10003,
                'gbif_id' => 20003,
                'specie_id' => 8,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'common_name' => 'Water Lily',
                'conservation_status' => 'Least Concern',
                'type' => 'Aquatic',
                'growth_form' => 'Perennial',
                'leaf_type' => 'Simple',
                'leaf_arrangement' => 'Alternate',
                'fruit_type' => 'Berry',
                'root_type' => 'Rhizome',
                'soil' => 'Silty',
                'sunlight' => 'Full Sun',
                'water' => 'High',
                'reproduction' => 'Sexual and Asexual',
                'height' => 0.3,
                'locale' => 'Eurasia and North Africa',
                'habitat' => 'Freshwater ponds and lakes',
                'diet' => 'Autotroph',
                'life_span' => 'Many years',
                'growth_time' => 1.5,
                'color' => 'White',
                'toxicity_level' => 'Non-toxic',
                'treatment_necessity' => 'None',
                'description' => 'Floating aquatic plant with large round leaves and white flowers.',
                'inaturalist_id' => 10004,
                'gbif_id' => 20004,
                'specie_id' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'common_name' => 'Aloe Vera',
                'conservation_status' => 'Least Concern',
                'type' => 'Succulent',
                'growth_form' => 'Perennial',
                'leaf_type' => 'Simple',
                'leaf_arrangement' => 'Rosette',
                'fruit_type' => 'Capsule',
                'root_type' => 'Fibrous',
                'soil' => 'Sandy',
                'sunlight' => 'Full Sun',
                'water' => 'Low',
                'reproduction' => 'Asexual',
                'height' => 0.6,
                'locale' => 'North Africa and Arabian Peninsula',
                'habitat' => 'Arid regions',
                'diet' => 'Autotroph',
                'life_span' => '5-25 years',
                'growth_time' => 2.0,
                'color' => 'Green',
                'toxicity_level' => 'Mildly toxic',
                'treatment_necessity' => 'Self-care',
                'description' => 'Succulent plant used for medicinal and cosmetic purposes.',
                'inaturalist_id' => 10005,
                'gbif_id' => 20005,
                'specie_id' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
