<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class Plant_suggestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::table("plant_suggestions")->insert([
            [
                'common_name' => 'Sunflower',
                'conservation_status' => 'Least Concern',
                'type' => 'Herb',
                'growth_form' => 'Annual',
                'leaf_type' => 'Simple',
                'leaf_arrangement' => 'Alternate',
                'fruit_type' => 'Achene',
                'root_type' => 'Taproot',
                'soil' => 'Loamy',
                'sunlight' => 'Full Sun',
                'water' => 'Medium',
                'reproduction' => 'Sexual',
                'height' => 3.0,
                'locale' => 'North America',
                'habitat' => 'Fields and grasslands',
                'diet' => 'Autotroph',
                'life_span' => 1.0,
                'growth_time' => 0.5,
                'color' => 'Yellow petals with brown center',
                'toxicity_level' => 'Non-toxic',
                'treatment_necessity' => 'None',
                'description' => 'Sunflowers are large, bright flowers known for tracking the sun.',
                'inaturalist_id' => 49219,
                'gbif_id' => 3117424,
                'photo' => 'https://upload.wikimedia.org/wikipedia/commons/4/40/Sunflower_sky_backdrop.jpg',
                'kingdom' => 'Plantae',
                'phylum' => 'Magnoliophyta',
                'class' => 'Magnoliopsida',
                'order' => 'Asterales',
                'family' => 'Asteraceae',
                'genu' => 'Helianthus',
                'specie' => 'Helianthus annuus',
            ],
            [
                'common_name' => 'Venus Flytrap',
                'conservation_status' => 'Vulnerable',
                'type' => 'Herb',
                'growth_form' => 'Perennial',
                'leaf_type' => 'Lobed',
                'leaf_arrangement' => 'Rosette',
                'fruit_type' => 'Capsule',
                'root_type' => 'Fibrous',
                'soil' => 'Peaty',
                'sunlight' => 'Full Sun',
                'water' => 'High',
                'reproduction' => 'Sexual and Asexual',
                'height' => 0.2,
                'locale' => 'Southeastern United States',
                'habitat' => 'Boggy wetlands',
                'diet' => 'Carnivorous',
                'life_span' => 7.0,
                'growth_time' => 1.0,
                'color' => 'Green leaves with red traps',
                'toxicity_level' => 'Non-toxic',
                'treatment_necessity' => 'None',
                'description' => 'The Venus flytrap is a carnivorous plant that captures insects.',
                'inaturalist_id' => 49087,
                'gbif_id' => 2870608,
                'photo' => 'https://upload.wikimedia.org/wikipedia/commons/1/19/Venus_Flytrap_showing_trigger_hairs.jpg',
                'kingdom' => 'Plantae',
                'phylum' => 'Magnoliophyta',
                'class' => 'Magnoliopsida',
                'order' => 'Caryophyllales',
                'family' => 'Droseraceae',
                'genu' => 'Dionaea',
                'specie' => 'Dionaea muscipula',
            ],
            [
                'common_name' => 'Coconut Palm',
                'conservation_status' => 'Not Evaluated',
                'type' => 'Tree',
                'growth_form' => 'Perennial',
                'leaf_type' => 'Pinnate',
                'leaf_arrangement' => 'Spiral',
                'fruit_type' => 'Drupe',
                'root_type' => 'Fibrous',
                'soil' => 'Sandy',
                'sunlight' => 'Full Sun',
                'water' => 'High',
                'reproduction' => 'Sexual',
                'height' => 30.0,
                'locale' => 'Tropical coastal regions',
                'habitat' => 'Beaches and sandy soils',
                'diet' => 'Autotroph',
                'life_span' => 80.0,
                'growth_time' => 6.0,
                'color' => 'Green leaves, brown trunk',
                'toxicity_level' => 'Non-toxic',
                'treatment_necessity' => 'None',
                'description' => 'The coconut palm produces coconuts and is vital to many tropical economies.',
                'inaturalist_id' => 49077,
                'gbif_id' => 2875837,
                'photo' => 'https://upload.wikimedia.org/wikipedia/commons/5/5a/Cocos_nucifera_Coconut_Palm.jpg',
                'kingdom' => 'Plantae',
                'phylum' => 'Magnoliophyta',
                'class' => 'Liliopsida',
                'order' => 'Arecales',
                'family' => 'Arecaceae',
                'genu' => 'Cocos',
                'specie' => 'Cocos nucifera',
            ],
        ]);
    }
}
